### ISSUE TITLE
Failed unit test cases

### ISSUE THREAD

**Issue by wangyu60** [GovTechSG/csharp-apex-api-security#6]
# Expected Behavior

all test cases to pass

# Current Behavior

10 test cases failed. see below secction

# Failure Information (for bugs)

Test Name:	BaseString_BugTest
Test FullName:	ApiUtilLibTest.BaseStringTest.BaseString_BugTest
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\BaseStringTest.cs : line 38
Test Outcome:	Failed
Test Duration:	0:00:00.023

Result StackTrace:	at ApiUtilLibTest.BaseStringTest.BaseString_BugTest() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\BaseStringTest.cs:line 64
Result Message:	
Expected string length 253 but was 289. Strings differ at index 55.
  Expected: "...com/api/v1/rest/level1/in-in/&ap=裕廊坊 心邻坊&auth_prefix_app_i..."
  But was:  "...com/api/v1/rest/level1/in-in/&Action=SendMessage&MessageBo..."
  --------------------------------------------^

Test Name:	GetL1Signature
Test FullName:	ApexUtilLibTest.TestDataTest.GetL1Signature
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs : line 195
Test Outcome:	Failed
Test Duration:	0:00:00.244

Result StackTrace:	
at ApexUtilLibTest.TestDataService.LoadTestFile(String path) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataService.cs:line 44
   at ApexUtilLibTest.BaseService.GetJsonFile(String fileName) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\BaseService.cs:line 118
   at ApexUtilLibTest.TestDataTest.GetL1Signature() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs:line 196
Result Message:	System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\nsearch\OneDrive\Projects\GovTech\testData\getL1Signature.json'.

Test Name:	GetL2Signature
Test FullName:	ApexUtilLibTest.TestDataTest.GetL2Signature
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs : line 238
Test Outcome:	Failed
Test Duration:	0:00:00.01

Result StackTrace:	
at ApexUtilLibTest.TestDataService.LoadTestFile(String path) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataService.cs:line 44
   at ApexUtilLibTest.BaseService.GetJsonFile(String fileName) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\BaseService.cs:line 118
   at ApexUtilLibTest.TestDataTest.GetL2Signature() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs:line 239
Result Message:	System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\nsearch\OneDrive\Projects\GovTech\testData\getL2Signature.json'.

Test Name:	Test_L1_Basic_Test
Test FullName:	ApiUtilLibTest.AuthorizationToken.Test_L1_Basic_Test
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\AuthorizationTokenTest.cs : line 44
Test Outcome:	Failed
Test Duration:	0:00:00.419

Result StackTrace:	at ApiUtilLibTest.AuthorizationToken.Test_L1_Basic_Test() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\AuthorizationTokenTest.cs:line 58
Result Message:	
Expected string length 331 but was 337. Strings differ at index 52.
  Expected: "...ttp://example.api.test/token",api_prefix_l1_timestamp="150..."
  But was:  "...ttp://example.api.test/token", api_prefix_l1_app_id="app-i..."
  --------------------------------------------^

Test Name:	Test_L2_Basic_Test
Test FullName:	ApiUtilLibTest.AuthorizationToken.Test_L2_Basic_Test
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\AuthorizationTokenTest.cs : line 63
Test Outcome:	Failed
Test Duration:	0:00:00.085

Result StackTrace:	at ApiUtilLibTest.AuthorizationToken.Test_L2_Basic_Test() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\AuthorizationTokenTest.cs:line 77
Result Message:	
Expected string length 974 but was 980. Strings differ at index 52.
  Expected: "...ttp://example.api.test/token",api_prefix_l2_timestamp="150..."
  But was:  "...ttp://example.api.test/token", api_prefix_l2_app_id="app-i..."
  --------------------------------------------^

Test Name:	Test_L2_Not_Supported_Cert_Test
Test FullName:	ApiUtilLibTest.AuthorizationToken.Test_L2_Not_Supported_Cert_Test
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\AuthorizationTokenTest.cs : line 101
Test Outcome:	Failed
Test Duration:	0:00:00.159

Result StackTrace:	at ApiUtilLibTest.AuthorizationToken.Test_L2_Not_Supported_Cert_Test() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\AuthorizationTokenTest.cs:line 104
Result Message:	
Expected: <System.ArgumentNullException>
  But was:  <System.Security.Cryptography.CryptographicException: Cannot find the requested object.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertBlobType(Byte[] rawData)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at ApiUtilLib.ApiAuthorization.PrivateKeyFromP12(String certificateFileName, String password) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLib\ApiAuthorization.cs:line 117
   at ApiUtilLibTest.AuthorizationToken.<>c__DisplayClass16_0.<Test_L2_Not_Supported_Cert_Test>b__0() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\AuthorizationTokenTest.cs:line 106
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args) in C:\src\nunit\nunit\src\NUnitFramework\framework\Assert.Exceptions.cs:line 51>

Test Name:	TestBaseString
Test FullName:	ApexUtilLibTest.TestDataTest.TestBaseString
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs : line 16
Test Outcome:	Failed
Test Duration:	0:00:00.004

Result StackTrace:	
at ApexUtilLibTest.TestDataService.LoadTestFile(String path) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataService.cs:line 44
   at ApexUtilLibTest.BaseService.GetJsonFile(String fileName) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\BaseService.cs:line 118
   at ApexUtilLibTest.TestDataTest.TestBaseString() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs:line 17
Result Message:	System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\nsearch\OneDrive\Projects\GovTech\testData\getSignatureBaseString.json'.

Test Name:	TestTokenSignature
Test FullName:	ApexUtilLibTest.TestDataTest.TestTokenSignature
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs : line 149
Test Outcome:	Failed
Test Duration:	0:00:00.006

Result StackTrace:	
at ApexUtilLibTest.TestDataService.LoadTestFile(String path) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataService.cs:line 44
   at ApexUtilLibTest.BaseService.GetJsonFile(String fileName) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\BaseService.cs:line 118
   at ApexUtilLibTest.TestDataTest.TestTokenSignature() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs:line 150
Result Message:	System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\nsearch\OneDrive\Projects\GovTech\testData\getSignatureToken.json'.

Test Name:	VerifyL1Signature
Test FullName:	ApexUtilLibTest.TestDataTest.VerifyL1Signature
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs : line 59
Test Outcome:	Failed
Test Duration:	0:00:00.002

Result StackTrace:	
at ApexUtilLibTest.TestDataService.LoadTestFile(String path) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataService.cs:line 44
   at ApexUtilLibTest.BaseService.GetJsonFile(String fileName) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\BaseService.cs:line 118
   at ApexUtilLibTest.TestDataTest.VerifyL1Signature() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs:line 60
Result Message:	System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\nsearch\OneDrive\Projects\GovTech\testData\verifyL1Signature.json'.

Test Name:	VerifyL2Signature
Test FullName:	ApexUtilLibTest.TestDataTest.VerifyL2Signature
Test Source:	E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs : line 102
Test Outcome:	Failed
Test Duration:	0:00:00.002

Result StackTrace:	
at ApexUtilLibTest.TestDataService.LoadTestFile(String path) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataService.cs:line 44
   at ApexUtilLibTest.BaseService.GetJsonFile(String fileName) in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\BaseService.cs:line 118
   at ApexUtilLibTest.TestDataTest.VerifyL2Signature() in E:\HPB\EDH\csharp-apex-api-security-master\ApiUtilLibTest\TestDataTest.cs:line 103
Result Message:	System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\nsearch\OneDrive\Projects\GovTech\testData\verifyL2Signature.json'.

## Steps to Reproduce

Download source code to a new computer and run test.

## Context

NA

## Failure Logs

will provide test report if needed

**Comment by robincher** [comment]
Hi @wangyu60,

The error is partly due to having the wrong test data path. Thanks for finding this out, we will fix this as soon as possible.

Meanwhile , you may download the test data at https://github.com/GovTechSG/test-suites-apex-api-security/tree/master/testData, and stored them locally before you run the test.

Hi @punjabisingh , can you update the test data to a relative path if possible? I am not sure if C# allows libraries to be pulled like Node/Java, if it is unable to, we can copy the data into this repository directly.

**Comment by kelvinwijaya** [comment]
I have added the test data which auto-download from the git repo which store temporarily in build temp folder, after doing testing found out that some test-cases are not passing which I fix as part of Issue #7 for Enhancement request

@punjabisingh , kindly help to check the failed test-cases

**Comment by kelvinwijaya** [comment]
@wangyu60 , you can pull our latest code first to have temporary fix.. anyway my team @punjabisingh  will work on fixing the test-cases

**Comment by wangyu60** [comment]
@kelvinwijaya sure. thank you.

**Comment by kelvinwijaya** [comment]
Updated the test-cases to fix the issue
